Feature/tests
rewqqx/OnlineShop pull request #12
Opened 2023-04-13 12:41 UTC by ACE-777

tests for handlers

2023-04-13 19:13 UTC, bogdanspbm requested changes

2023-04-13 19:13 UTC, bogdanspbm commented on backend/src/utils/requests_test.go
> +type Item struct {
Нахуя это тут, если это уже есть?

2023-04-13 19:13 UTC, bogdanspbm commented on backend/src/utils/requests_test.go
> +	databaseConnection := database.DBConnect{Ip: host, Port: "5433", Password: "pgpass", User: "postgres", Database: "postgres"}
???

2023-04-13 19:13 UTC, bogdanspbm commented on backend/src/utils/requests_test.go
> +	host := "127.0.0.1"
Host можно вынести как константу, раз она переиспользуется + код по созданию бд и сервера тоже в отдельную функцию.

2023-04-13 19:13 UTC, bogdanspbm commented on backend/src/utils/requests_test.go
> +	host := "127.0.0.1"
Типа отсюда ->

2023-04-13 19:13 UTC, bogdanspbm commented on backend/src/utils/requests_test.go
> +	go server.Start(8080)
-> до сюда отдельная функция

2023-04-13 19:13 UTC, bogdanspbm commented on backend/src/utils/requests_test.go
> +	require.Equal(t, JSONExample, bodyString)
Это плохо:
1) У тебя JSONExample это строка которую тяжело читать. Ты бы мог сделать экземпляр Item-а, поставить руками ID имя и тд. Замаршалить ответ в Структуру и сравнить.

2) У тебя тест одноразовый. Когда мы добавим новое поле у Item он перестанет работать. Нужно брать предмет из BD (тем более ты уже создал коннект) и сравнивать с тем что дает ручка.

2023-04-13 19:13 UTC, bogdanspbm commented on backend/src/utils/requests_test.go
> +	payload := map[string]any{
Зачем map-а, если у нас есть объект данного типа? Если там есть лишние поля, То сделай ему метод toCreateJSON например.

2023-04-13 19:13 UTC, bogdanspbm commented on backend/src/utils/requests_test.go
> +	payload := map[string]any{
Аналогично, нужно работать не от мапы, а от объекта. + Дубликат кода

2023-04-13 19:13 UTC, bogdanspbm commented on docker-compose.yml
>      depends_on:
Это убери из коммита. Запрещается это мерджить в мэйн.

2023-04-20 18:56 UTC, ACE-777 commented on backend/src/utils/requests_test.go
> +	go server.Start(8080)
1

2023-04-20 18:56 UTC, ACE-777 commented on backend/src/utils/requests_test.go
> +	host := "127.0.0.1"
1

2023-04-20 18:56 UTC, ACE-777 commented on backend/src/utils/requests_test.go
> +	host := "127.0.0.1"
1

2023-04-20 18:56 UTC, ACE-777 commented on backend/src/utils/requests_test.go
> +	databaseConnection := database.DBConnect{Ip: host, Port: "5433", Password: "pgpass", User: "postgres", Database: "postgres"}
1

2023-04-20 18:56 UTC, ACE-777 commented on backend/src/utils/requests_test.go
> +type Item struct {
1

2023-04-20 18:56 UTC, ACE-777 commented on backend/src/utils/requests_test.go
> +	payload := map[string]any{
1

2023-04-20 18:56 UTC, ACE-777 commented on backend/src/utils/requests_test.go
> +	payload := map[string]any{
1

2023-04-20 18:56 UTC, ACE-777 commented on backend/src/utils/requests_test.go
> +	require.Equal(t, JSONExample, bodyString)
1

2023-04-20 18:57 UTC, closed without merging